# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05_makemore.activations.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/05_makemore.activations.ipynb 3
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import torch
import torch.nn.functional as F
from .bigram import stoi, itos
from .mlp import build_XY, Model, plot_embeddings, train, gen_word_nn
from sklearn.cluster import KMeans
from sklearn.manifold import TSNE
