# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03_makemore.bigram.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/03_makemore.bigram.ipynb 3
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import torch
