# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/04_makemore.mlp.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/04_makemore.mlp.ipynb 3
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import torch
import torch.nn.functional as F
from .bigram import stoi, itos
