# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/minion',
                'doc_host': 'https://Rahuketu86.github.io',
                'git_url': 'https://github.com/Rahuketu86/minion',
                'lib_path': 'minion'},
  'syms': {'minion.core': {'minion.core.foo': ('core.html#foo', 'minion/core.py')}}}
