# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['Value', 'foo']

# %% ../nbs/00_core.ipynb 19
class Value:
    '''Class to hold a scalar number in an object. Supports arthmetic operations like addition, multiplications etc...'''
    def __init__(self, data) -> None:
        self.data = data

    def __repr__(self) -> str:
        return f"Value(data={self.data})"
    
    def __add__(self, other):
        '''Protocol to add 2 value objects'''
        return Value(self.data + other.data)
    
    def __mul__(self, other):
        '''Protocal to multiply 2 value objects'''
        return Value(self.data*other.data)

# %% ../nbs/00_core.ipynb 21
def foo(): pass
